---
title: "Time dependent model applied to 1:1 orthogroups V2.0"
output: html_document
---

# Goal of analysis

Make a model that can distinguish genes with a different cold response in the basal and core pooids.



```{r loadLibraries, echo =FALSE, message=FALSE}
library(stringr)
library(DESeq2)
source("/mnt/users/lagr/GRewd/pipeline/R/orthoGrpTools.R")
```


```{r loadData, echo=FALSE, cache=TRUE}
pipelineOutDir <- "/mnt/NOBACKUP/mariansc/share"
grps <- loadOrthoGrpsArray(orthoGrpFile = file.path(pipelineOutDir,"orthos/orthoMCL/groups.txt"))

tblDir <- file.path(pipelineOutDir,"orthos/exprTbls")

grp11Cnt <- read.table(file = file.path(tblDir,"grpSingletonCountTbl.txt"), 
                       stringsAsFactors = F)
# grp11FPKM <- read.table(file = file.path(tblDir,"grpSingletonFPKMTbl.txt"), 
#                        stringsAsFactors = F)
# grpSumCnt <- read.table(file = file.path(tblDir,"grpSumCountTbl.txt"), 
#                        stringsAsFactors = F)
# grpSumFPKM <- read.table(file = file.path(tblDir,"grpSumFPKMTbl.txt"), 
#                        stringsAsFactors = F)

# files <- dir(tblDir,pattern="_expected_countTbl.txt",full.names = T)
# exprCnt <- lapply(setNames(files,str_extract(basename(files),"^[^_]+")), 
#                   read.table, stringsAsFactors = F)

# remove WC samples, cast to matrix and log transform
# lapply(exprCnt, function(X){
#   log2( 1+as.matrix( X[ , !grepl("^wc_",names(X)) ] ) )
# }) -> expr

# files <- dir(tblDir,pattern="_FPKMTbl.txt",full.names = T)
# exprFPKM <- lapply(setNames(files,str_extract(basename(files),"^[^_]+")), 
#                   read.table, stringsAsFactors = F)

spcs <- c("BrDi","HoVu","MeNu1","MeNu2","StLa","NaSt")
spcs <- setNames(spcs,spcs)

# get number of genes per species per group
lens <- unlist(lapply(grps,length))
dim(lens) <- dim(grps)
dimnames(lens) <- dimnames(grps)

```

```{r fitModels, echo=FALSE, cache=TRUE, message=FALSE}
countData <- grp11Cnt
names(countData) <- sub("T\\.1","T-1",names(countData))

colData <- as.data.frame(str_split_fixed(names(countData),"\\.",4)[ ,1:3])
names(colData) <- c("spcPop","timePoint","mix")
colData$spcAsm <- as.factor(str_extract(colData$spcPop,paste(spcs,collapse="|")))
colData$core <- colData$spcAsm %in% c("BrDi","HoVu")

TtoX <- c(`T-1`=0,T0=1,T1=2,T3=3,T4=4)
TtoF <- c(`T-1`="pre",T0="pre",T1="peak",T3="late",T4="late")
TtoF2 <- c(`T-1`="ramp0",T0="peak0",T1="peak1",T3="ramp1",T4="ramp1")


colData$Tf <- as.factor(TtoF[colData$timePoint])
colData$Tf2 <- as.factor(TtoF2[colData$timePoint])

ddsAll <- DESeqDataSetFromMatrix(countData = round(countData),
                                colData = colData,
                                design = formula(~ Tf2 ))

ddsAll <- estimateSizeFactors(ddsAll)
ddsAll <- estimateDispersions(ddsAll)
vsd <- varianceStabilizingTransformation(ddsAll)

m <- assay(vsd)
dim(m)
colnames(m) <- names(countData)
heatmap(m,scale = "none")

ddsAll <- DESeq(ddsAll)
idx <- (results(ddsAll,contrast = c("Tf2","peak0","peak1"))$padj < 0.01)
table(idx)
heatmap(m[idx,],scale = "none")
```

```{r fitEachSpc, echo=FALSE, eval=FALSE}

lapply(spcs,function(spc){
  dds <- DESeqDataSetFromMatrix(countData = round(countData[ ,colData$spcAsm==spc]),
                                colData = colData[colData$spcAsm==spc,],
                                design = formula(~ Tf ))
  

  dds <- DESeq(dds)
  return(dds)
}) -> dds

resultsNames(dds$BrDi)
BdRampFC <- results(dds$BrDi,contrast = c("Tf","pre","late"))$log2FoldChange
BdRampPval <- results(dds$BrDi,contrast = c("Tf","pre","late"))$pvalue
HvRampFC <- results(dds$HoVu,contrast = c("Tf","pre","late"))$log2FoldChange
HvRampPval <- results(dds$HoVu,contrast = c("Tf","pre","late"))$pvalue
idx <- (BdRampPval<0.01 & HvRampPval<0.01)
plot(BdRampFC[idx],HvRampFC[idx])
plot(BdRampFC,HvRampFC)
cor.test(BdRampFC,HvRampFC,use = "pairwise.complete.obs")
plot(BdRampPval,HvRampPval)
table(BdRampPval<0.01,HvRampPval<0.01)

colnames(m$MeNu2)

cor.test(log10(m$HoVu[ ,"pPeak"]),log10(m$NaSt[ ,"pPeak"]),use = "pairwise.complete.obs")
idx <- m$HoVu[ ,"pTime"]<0.01 & m$MeNu1[ ,"pTime"]<0.01
idx <- which(idx)
plot(m$MeNu2[idx,"t_sTRUE"],m$MeNu2[idx,"t_l"])
segments(x0=m$MeNu1[idx,"t_sTRUE"],y0=m$MeNu1[idx,"t_l"],
         x1=m$MeNu2[idx,"t_sTRUE"],y1=m$MeNu2[idx,"t_l"],col="red")
```

```{r def_plotGrp11ProfilesModel, echo=FALSE}
plotGrp11ProfilesModel <- function(grp, countData, betas){

  layout(matrix(c(1:6), 1, 6, byrow = T),
     widths=rep(2,6), heights=c(2.5))
  par(mar=c(5, 3, 4, 0))
  
  TtoX <- c(T0=1,T1=2,T3=3,T4=4)

  expr <- log2(1+countData[grp, ])
  b <- betas[grp, ]

  # get same scale for all species
  ylim <- range(expr)
  
  
  for(spc in spcs){
    expCnt <- expr[ colData$spcAsm == spc]
    
    plot(x=NULL,xaxt="n",main=spc,xlab="",xlim=range(TtoX),
         ylim=ylim)
    if(spc==spcs[1])title(ylab="log2(expCnt+1)",line=2)
    axis(1,at=TtoX,labels=names(TtoX)) 
    timePoint = str_extract(colnames(expCnt),"T[0-4]")

    
    t_l <- b["t_l"]+(spc %in% c("BrDi","HoVu"))*b["t_lcore"] 
    t_s <- b["t_sTRUE"]+(spc %in% c("BrDi","HoVu"))*b["t_score"]
    a <- b[grep(spc,names(b))]
    abline(b=TtoX * t_l, a=a,col="red")
    arrows(y0=a+2*t_l, y1=a+2*t_l+t_s, x0=2,x1=2,col="red",length=0.1)
    

    points(x=TtoX[timePoint],y=expCnt)
    xMean <- tapply(as.numeric(expCnt),timePoint,mean)
    lines(x=TtoX[names(xMean)],y=xMean)
  }

  # reset graphics parameters
  layout(1)
  par(mar=c(5, 4, 4, 2) + 0.1)
}

```

## Model test 1

```{r plot1, echo=FALSE,fig.height=2.5,fig.width=9}
tbl <- results(dds1)[order(results(dds1)$pvalue)[1:5],]
tbl

betas=coef(dds1)

for(grp in rownames(tbl)){
  plotGrp11ProfilesModel(grp, countData, betas)
}
```

Note that T1 of HoVu is an outlier. PCA plot:
```{r plot_PCA, echo=TRUE, fig.height=7, fig.width=7}
plotPCA(varianceStabilizingTransformation(dds),c("spcAsm"))
plotPCA(varianceStabilizingTransformation(dds),c("timePoint"))
```

## Model test 2


```{r plot2, echo=FALSE,fig.height=2.5,fig.width=9}

tbl <- results(dds2)[order(results(dds2)$pvalue)[1:5],]
tbl

betas=coef(dds2)

for(grp in rownames(tbl)){
  plotGrp11ProfilesModel(grp, countData, betas)
}
```


```{r deadCode, echo=FALSE, eval=FALSE}
grp = "grp110242"
plotGrp11Profiles(grp, countData, colData)
plotGrp11Profiles <- function(grp, countData, colData){

  layout(matrix(c(1:6), 1, 6, byrow = T),
     widths=rep(2,6), heights=c(2.5))
  par(mar=c(5, 3, 4, 0))
  
  TtoX <- c(T0=1,T1=2,T3=3,T4=4)

  expr <- log2(1+countData[grp, ])

  # get same scale for all species
  ylim <- range(expr)
  
  
  for(spc in spcs){
    expCnt <- expr[ colData$spcAsm == spc]

    plot(x=NULL,xaxt="n",main=spc,xlab="",xlim=range(TtoX),
         ylim=ylim)
    if(spc==spcs[1])title(ylab="log2(expCnt+1)",line=2)
    axis(1,at=TtoX,labels=names(TtoX)) 
    timePoint = str_extract(colnames(expCnt),"T[0-4]")

    points(x=TtoX[timePoint],y=expCnt)
    xMean <- tapply(as.numeric(expCnt),timePoint,mean)
    lines(x=TtoX[names(xMean)],y=xMean)
  }

  # reset graphics parameters
  layout(1)
  par(mar=c(5, 4, 4, 2) + 0.1)
}


```

